delete from users where uid > 2;
delete from field_data_field_user_chapter where entity_id > 2;
delete from field_revision_field_user_chapter where entity_id > 2;
delete from field_data_field_user_phone where entity_id > 2;
delete from field_revision_field_user_phone where entity_id > 2;
delete from field_data_field_copied_over where entity_id > 2;
delete from field_revision_field_copied_over where entity_id > 2;
delete from field_data_field_user_subscribed where entity_id > 2;
delete from field_revision_field_user_subscribed where entity_id > 2;
